name: haus_party
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.1
  flutter_credit_card: ^2.0.0
  qr_flutter: ^4.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  google_maps_flutter: ^2.0.6
  flushbar: ^1.10.4
  google_fonts: ^2.1.0
  http: ^0.13.3
  share: ^2.0.4
  riverpod: ^0.14.0+3
  flutter_riverpod: ^0.14.0+3
  hooks_riverpod: ^0.14.0+4
  flutter_hooks: ^0.17.0
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.4
  modal_bottom_sheet: ^2.0.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/party_1.png
    - assets/profile_image.jpg
    - assets/asset-1.png
    - assets/asset-2.png
    - assets/asset-10.png
    - assets/drink_image.png
    - assets/ciroc_peach.png
    - assets/dirty_martini.png
    - assets/dusse.png
    - assets/henessy.png
    - assets/dom_perignon.png
    - assets/asset-3.png
    - assets/party_background.jpg
    - assets/backgroundNewLogin.png
    - assets/backgroundInital.png
    - assets/mapBack.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
